"use server"

import { getSupabaseServerClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"

export async function savePracticeSession(letters: string[]) {
    const supabase = await getSupabaseServerClient()

    // 1. Get User
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: "Not authenticated" }

    // 2. Insert Session
    // The 'letters' column stores diagnosed letter issues (e.g., ["KAF", "RA"])
    // created_at is auto-generated by Supabase (DEFAULT NOW())
    const { error } = await supabase.from("practice_sessions").insert({
        user_id: user.id,
        letters: letters,
    })

    if (error) {
        console.error("Error saving session:", error)
        return { error: error.message }
    }

    // 3. Refresh Dashboard so it knows we have a new session
    revalidatePath("/dashboard")
    return { success: true }
}